default:
  homepage:
    title: "Xceptance - The Software Testing Experts"
  aboutUsPage:
    title: "Xceptance - Who we are"
  twitterPage:
    title: "Xceptance"
  teamPage:
    headline: "Behind the Scenes"
    
    